name: Build rock on PR

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Determine any rockcraft.yaml changed in the PR
      id: changed-files
      uses: tj-actions/changed-files@v47
      with:
        files: "./rockcraft.yaml"

    - name: Setup LXD
      if: steps.changed-files.outputs.any_changed
      uses: canonical/setup-lxd@v0.1.3
      with:
        channel: latest/stable

    - name: Install dependencies
      if: steps.changed-files.outputs.any_changed
      run: |
        sudo snap install --classic rockcraft
    - name: Build ROCK
      if: steps.changed-files.outputs.any_changed
      run: |
        rockcraft pack --verbose
